/**
 * @desc Reducers Action List
 */

// Doctor
export const SET_DOCTOR_LOADER = "SET_DOCTOR_LOADER";
export const SET_DOCTOR_USER = "SET_DOCTOR_USER";
export const SET_DOCTOR_PROFILE = "SET_DOCTOR_PROFILE";
export const SET_DOCTOR_RES_ERROR = "SET_DOCTOR_RES_ERROR";
// export const SET_AUTH_RES_ERROR = "SET_AUTH_RES_ERROR";
// export const SET_AUTH_RES_SUCCESS = "SET_AUTH_RES_SUCCESS";
// export const CLEAR_AUTH_RES_MSG = "CLEAR_AUTH_RES_MSG";
// export const CLEAR_AUTH_DATA = "CLEAR_AUTH_DATA";

//Admin
export const SET_ADMIN_LOADER = "SET_ADMIN_LOADER";
export const SET_ADMIN_USER = "SET_ADMIN_USER";
export const SET_ADMIN_PROFILE = "SET_ADMIN_PROFILE";
export const SET_ADMIN_RES_ERROR = "SET_ADMIN_RES_ERROR";
export const SET_ADMIN_PATIENTS = "SET_ADMIN_PATIENTS";
export const SET_ADMIN_DOCTORS = "SET_ADMIN_DOCTORS";
export const SET_ADMIN_EBILL = "SET_ADMIN_EBILL";
// export const SET_PROFILE_RES_SUCCESS = "SET_PROFILE_RES_SUCCESS";
// export const CLEAR_PROFILE_RES_MSG = "CLEAR_PROFILE_RES_MSG";
// export const CLEAR_PROFILE_DATA = "CLEAR_AUTH_DATA";

//Patient
export const SET_PATIENT_LOADER = "SET_PATIENT_LOADER";
export const SET_PATIENT_USER = "SET_PATIENT_USER";
export const SET_PATIENT_PROFILE = "SET_PATIENT_PROFILE";
export const SET_PATIENT_RES_ERROR = "SET_PATIENT_RES_ERROR";

//Ebill
// export const SET_QUEUE_CATEGORIES = "SET_QUEUE_CATEGORIES";
// export const SET_QUEUE_LIST = "SET_QUEUE_LIST";
// export const CLEAR_QUEUE_DATA = "CLEAR_QUEUE_DATA";

export const SET_COMMON_TYPE = "SET_COMMON_TYPE";
